### ISSUE TITLE
0w0

### ISSUE THREAD

**Issue by RatserX** [Xerasin/GCinemaCraftDownloader#1]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the `Prototypes.func` wiff a more \~streamylined\~ kawaii `Pwototypiee.funkywunks` object that make the JS go sooper dooper fast!! XD \*starts twerking\*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by addy-dclxvi** [comment]
We need more pull request like this!

**Comment by ghost** [comment]
LMAO, this got on /r/ProgrammerHumor

**Comment by Cleroth** [comment]
It doesn't get any cringier than this.

**Comment by Ueaj-Kerman** [comment]
It's time to stop

**Comment by dextel2** [comment]
This is like nails on the chalkboard for me

**Comment by YellowPapaya** [comment]
Good

**Comment by Unicode-Hater** [comment]
What in the name of fuck

**Comment by RusseII** [comment]
WTF reminds me of https://iostexts.com

**Comment by YellowPapaya** [comment]
Why is this suddenly blowing up again lol

**Comment by abdyfranco** [comment]
In the name of God, What the fuck!!!

**Comment by laike9m** [comment]
Btw, I didn't see a pull request 🤔

**Comment by Hans5958** [comment]
sad tyre

**Comment by aneutron** [comment]
I think I'm drunk. It has to be it. That's the only viable explanation.

**Comment by aria-zinoviev** [comment]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! `And God said, "At the time of fullness, cleanse the world with my rage." `

I repwaced the `Prototypes.func` wiff a more ~`Gather forth the White Oil, the Black Cup and the Blood of the Ten Sinners.` ~ kawaii `Pwototypiee.funkywunks` object that make the JS go sooper dooper fast!! XD `Prepare for the Ritual of the Holy Assumption`

Can u pwease merge my pwull wequest senpai?!! 'And God said, "Offer the Blood of the Ten Sinners and the White Oil."`

**Comment by Quezler** [comment]
> 404, recent comment from email notification not found.

**Comment by MCUmbrella** [comment]
OwO what's this

**Comment by MERZAK-X** [comment]
Omg, I still laugh att his every time xD

**Comment by susenj** [comment]
lmao...this is freaking hilarious everytime I come across.

**Comment by nocturn9x** [comment]
lmao

**Comment by Volker-Weissmann** [comment]
For reference: https://www.reddit.com/r/ProgrammerHumor/comments/ll34yc/would_you_merge_with_them/

**Comment by pankajhirway** [comment]
Github is the new social media?

**Comment by kquote03** [comment]
> Github is the new social media?

Always has been

**Comment by Koocy** [comment]
Bu ne la jskjfhdjfgkjdkjgf

**Comment by lexigren** [comment]
Go back to reddit.

**Comment by KevLehman** [comment]
I wonder if he has the benchmark proving that after the change it will go `sooper dooper fast`

**Comment by LeWarpy** [comment]
what the fuck

**Comment by Eulehund99** [comment]
big oof

**Comment by crazybolillo** [comment]
Hi mom

**Comment by bzbug** [comment]
@CrazyBolillo, hi sweety

**Comment by esebelekewek** [comment]
lol

**Comment by Snoresville** [comment]
What the fuck

**Comment by Volker-Weissmann** [comment]
Is @bzbug  actually @CrazyBolillo 's mum?

**Comment by bzbug** [comment]
@Volker-Weissmann, I may have not given him birth, but I love him as my own

**Comment by milahnmartin** [comment]
Bro this has to be the best thing ever lmao

**Comment by Volker-Weissmann** [comment]
Is the original PR real? If want to look at the code.

**Comment by algebraic-dev** [comment]
UwU

**Comment by loralighte** [comment]
Legendary

**Comment by sunny52525** [comment]
*starts twerking*

**Comment by eatmyvenom** [comment]
Im curious if that is the most reacted to github post

**Comment by bzbug** [comment]
it's not: MrMEEE/bumblebee-Old-and-abbandoned#123

**Comment by dnrm** [comment]
whattt

**Comment by AnassHmida** [comment]
this made my night 😂

**Comment by faisalsayed10** [comment]
Looking at this after 3 years and still laughing.

**Comment by fxtressia** [comment]
This is illegal.

**Comment by GCJ2** [comment]
How do I see the files changed?

**Comment by Alcaro** [comment]
You don't. This is an issue, not a pull request.

**Comment by GCJ2** [comment]
oh

**Comment by HelveticaToast** [comment]
why wasn't this merged?

**Comment by faisalsayed10** [comment]
Cuz this is an issue

**Comment by dreemurfangroyper** [comment]
May Allah severely punish and humiliate you for all eternity 💯

**Comment by Blizzsuxx** [comment]
inshallah

**Comment by morkev** [comment]
Legend says they are still twerking to this very day.

**Comment by twisted-nematic57** [comment]
Yeah it was reposted another time...

**Comment by sudo-Mystic** [comment]
stop reposting it 



_starts twerking_

**Comment by Imusing** [comment]
why is this so popular?? I don't understand I don't even know what this repository is about

**Comment by ziscky** [comment]
This is being used to karma farm again smh

**Comment by GCJ2** [comment]
> This is being used to karma farm again smh 

No, it's changing the world

**Comment by yikerman** [comment]
> why is this so popular?? I don't understand I don't even know what this repository is about

@GoombaProgrammer In case you don't know, it's shitposted again at [r/ProgrammerHumor/comments/11swejr/not_something_i_expected_to_be_googling_today](https://www.reddit.com/r/ProgrammerHumor/comments/11swejr/not_something_i_expected_to_be_googling_today/?utm_source=share&utm_medium=web2x&context=3)

**Comment by xvrx** [comment]
*starts twearking*

**Comment by tryproxy** [comment]
_twerking with confusion since 2017_

**Comment by iwin2471** [comment]
miku chan please my code works fine even not my machine UwU. (pray while twearking)

**Comment by lucasriondel** [comment]
UwU

**Comment by Cartrigger** [comment]
What the fuck
Also hello 2024

**Comment by Nandan-N** [comment]
Ooof 💀

**Comment by Glass109** [comment]
Thought this was posted on the React repo lol

**Comment by rakibdev** [comment]
How did I get here??? I was watching Iron Man YouTube vids.

**Comment by frickypickle** [comment]
Referenced in https://youtu.be/AgyJv2Qelwk 1:38 had to see if it was real

**Comment by lnfel** [comment]
> Referenced in https://youtu.be/AgyJv2Qelwk 1:38 had to see if it was real

I was here for the same r3ason UWU

**Comment by suspiciousRaccoon** [comment]
> Referenced in https://youtu.be/AgyJv2Qelwk 1:38 had to see if it was real

I had to check aswell.

**Comment by LassazVegaz** [comment]
howy mowy sat on a waww

**Comment by Zweak** [comment]
> Referenced in https://youtu.be/AgyJv2Qelwk 1:38 had to see if it was real

Came here from the same vid

**Comment by Keramis** [comment]
Fresh ass comments on the PR

**Comment by prince-clumio** [comment]
This is some "Degenerate" level PR!

**Comment by AstrofoxDevelopment** [comment]
This is why I'm a dev today

**Comment by User8395** [comment]
Sweet Earth and everything on it what the fuck

**Comment by aeciobrito** [comment]
Submit the code as a RAWR file.

**Comment by brodante** [comment]
lmfaooooo this is still active XDDDDD

**Comment by yukiarimo** [comment]
Enough internet for today.

**Comment by kikones34** [comment]
> Referenced in https://youtu.be/AgyJv2Qelwk 1:38 had to see if it was real

Samesies uwu

**Comment by lilleanton** [comment]
LOL

**Comment by User8395** [comment]
Stop it's already closed

**Comment by vstyler96** [comment]
This is the pull request I deserve XD

**Comment by voidwyrm-2** [comment]
UwU

**Comment by MayCXC** [comment]
LGTM

**Comment by tizu69** [comment]
I hope they train ai on this.

**Comment by Rusinas** [comment]
Not the owiginal but okay UwU

**Comment by Artemis1-0** [comment]
Wow. Just wow.

**Comment by yuirsilva** [comment]
edging as I type this

**Comment by mfux** [comment]
I'm making copilot speak to me like this. 
Better hope AI does not turn out to be concious or I'm going to be sentenced for this in the future.
